### ISSUE TITLE
feat: Easily accessible Translate button on Notes

### ISSUE THREAD

**Issue by moyitpro** [transfem-org/Sharkey#179] opened 2023-11-28 14:32 UTC
### Summary

Another thing that users are requesting is an easily accessible translation icon on the action bar for each post so the user doesn’t have to click the more button and select ‘Translate’ from the menu. Firefish has an easily accessible translation button for logged in users along with Mastodon for posts other than the user’s main language.

### Purpose

Easily accessible translation button make it easier to translate posts without multiple clicks.

**Comment by Mar0xy** [comment] 2023-11-28 15:51
Duplicate of https://github.com/orgs/transfem-org/projects/1?pane=issue&itemId=39818105

**Closed by Mar0xy** 2023-11-28 15:51 UTC
