### ISSUE TITLE
bug?: About Sharkey page disappears on load

### ISSUE THREAD

**Issue by Freeplayg** [transfem-org/Sharkey#171] opened 2023-11-27 16:24 UTC
### 💡 Summary

video below

### 🥰 Expected Behavior

Page should load normally

### 🤬 Actual Behavior

Am not sure if any errors here are relevant 
[Screencast from 2023-11-27 11-21-33.webm](https://github.com/transfem-org/Sharkey/assets/40742947/5a3cd57d-4ec9-4805-a900-d8403c2ea4b9)

### 📝 Steps to Reproduce

Go to the about sharkey page

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Fedora 36, Gnome
* Browser: Firefox 120.0
* Server URL: plasmatrap.com
* Misskey: Sharkey v2023.11.2.beta1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by Insert5StarName** [comment] 2023-11-27 16:27
this maybe be an instance specific issue

**Comment by Insert5StarName** [comment] 2023-11-27 16:29
im not able to reproduce the issue imma get in contact with privateger

**Comment by Mar0xy** [comment] 2023-11-29 01:46
It seems that the about section now loads on plasmatrap so I will close this issue.

**Closed by Mar0xy** 2023-11-29 01:46 UTC
Labels: bug?
