### ISSUE TITLE
Default reaction

### ISSUE THREAD

**Issue by 1bcb** [transfem-org/Sharkey#141] opened 2023-11-05 14:24 UTC
### Summary

The vast majority of the time, when I leave a reaction on the fediverse, the reaction I want to use is the purple heart emoji💜.

The interface currently presents me with two reaction buttons: The heart-shaped button allows leaving a red heart reaction, and the "reaction" button opens a pop-up to pick a different reaction.  Hence, to leave any reaction other than the red heart, I need to make at least two clicks.  I can rearrange the pop-up so that the purple heart is first, but it still requires two clicks, compared to only one click for the red heart.

But what's so special about the red heart?  Why should the red heart be the only reaction available with a single click?

I propose a setting called something like "default reaction."  The setting shoudl allow users to pick the reaction they expect to use most frequently.  Instead of a red heart, the bottom of each post should have a one-click button to leave your default reaction.

**Comment by Mar0xy** [comment] 2023-11-05 18:23
Duplicate of #95

**Closed by Mar0xy** 2023-11-05 18:23 UTC

**Comment by 1bcb** [comment] 2023-11-05 23:43
I don't think it's a duplicate because #95 specifies "instance admins" can set a default reaction where as I am asking for users to be able to do it.

**Comment by Mar0xy** [comment] 2023-11-05 23:45
We prefer doing it per instance as this is what most of the instance admins requested.

Also from Discord from another person: "(still pretty much 'duplicate' though)"

**Comment by Insert5StarName** [comment] 2023-11-07 22:35
> I don't think it's a duplicate because #95 specifies "instance admins" can set a default reaction where as I am asking for users to be able to do it.

we may look into allowing users to overwrite the instance reaction but it would still be merged with issue #95
